package graph

// This file will be automatically regenerated based on the schema, any resolver
// implementations
// will be copied through when generating and any unknown code will be moved to the end.
// Code generated by github.com/99designs/gqlgen version v0.17.86

import (
	"context"
	"fmt"

	"forest-bd-viewer/internal/auth"
	"forest-bd-viewer/internal/geo"
	"forest-bd-viewer/internal/graph/model"
)

// AnalyzePolygon is the resolver for the analyzePolygon field.
func (r *mutationResolver) AnalyzePolygon(ctx context.Context, geojson string) (*model.PolygonAnalysis, error) {
	// Authentication required — only logged-in users may run spatial analyses.
	claims := auth.GetUser(ctx)
	if claims == nil {
		return nil, fmt.Errorf("authentication required")
	}

	geoQ := &geo.Queries{DB: r.DB}
	stats, err := geoQ.AnalyzePolygon(ctx, geojson)
	if err != nil {
		return nil, fmt.Errorf("polygon analysis failed: %w", err)
	}

	// ── Map geo.PolygonStats → model.PolygonAnalysis ────────────────────────

	// Forest-cover percentage relative to total polygon area (avoid ÷0).
	var coverPct float64
	if stats.AreaHa > 0 {
		coverPct = (stats.ForestCoverHa / stats.AreaHa) * 100
	}

	result := &model.PolygonAnalysis{
		AreaHa:         stats.AreaHa,
		ForestCoverHa:  stats.ForestCoverHa,
		ForestCoverPct: coverPct,
		ParcelCount:    int(stats.ParcelCount),
	}

	// TFV breakdown — compute % relative to total forest cover in polygon.
	for _, row := range stats.TFVBreakdown {
		var pct float64
		if stats.ForestCoverHa > 0 {
			pct = (row.AreaHa / stats.ForestCoverHa) * 100
		}
		result.TfvBreakdown = append(result.TfvBreakdown, &model.TfvBreakdown{
			CodeTfv: row.CodeTFV,
			LibTfv:  row.LibTFV,
			AreaHa:  row.AreaHa,
			Pct:     pct,
		})
	}

	// Species breakdown — compute % relative to total forest cover.
	for _, row := range stats.SpeciesBreakdown {
		var pct float64
		if stats.ForestCoverHa > 0 {
			pct = (row.AreaHa / stats.ForestCoverHa) * 100
		}
		result.SpeciesBreakdown = append(result.SpeciesBreakdown, &model.SpeciesBreakdown{
			Essence: row.Essence,
			AreaHa:  row.AreaHa,
			Pct:     pct,
		})
	}

	return result, nil
}
