package graph

// This file will be automatically regenerated based on the schema, any resolver
// implementations
// will be copied through when generating and any unknown code will be moved to the end.
// Code generated by github.com/99designs/gqlgen version v0.17.86

import (
	"context"
	"fmt"
	"forest-bd-viewer/internal/auth"
	"forest-bd-viewer/internal/geo"
	"forest-bd-viewer/internal/graph/model"
)

// AnalyzeLidar is the resolver for the analyzeLidar field.
func (r *mutationResolver) AnalyzeLidar(ctx context.Context, geojson string) (*model.LidarAnalysis, error) {
	// Authentication required
	claims := auth.GetUser(ctx)
	if claims == nil {
		return nil, fmt.Errorf("authentication required")
	}

	result, err := geo.AnalyzeLidar(ctx, geojson)
	if err != nil {
		return nil, fmt.Errorf("LiDAR analysis failed: %w", err)
	}

	out := &model.LidarAnalysis{
		HasCoverage: result.HasCoverage,
	}

	if result.Message != "" {
		out.Message = &result.Message
	}

	if result.HasCoverage && result.CHMImageID != "" {
		// Build the image URL — served by the backend
		ec := GetEchoContext(ctx)
		scheme := "http"
		host := "localhost:8080"
		if ec != nil {
			host = ec.Request().Host
			if ec.Request().TLS != nil {
				scheme = "https"
			}
		}
		imageURL := fmt.Sprintf("%s://%s/lidar/chm/%s.png", scheme, host, result.CHMImageID)
		out.ChmImageURL = &imageURL

		minH := result.MinHeight
		maxH := result.MaxHeight
		meanH := result.MeanHeight
		medianH := result.MedianHeight
		out.MinHeight = &minH
		out.MaxHeight = &maxH
		out.MeanHeight = &meanH
		out.MedianHeight = &medianH

		out.Bounds = []float64{
			result.Bounds[0], result.Bounds[1],
			result.Bounds[2], result.Bounds[3],
		}
	}

	return out, nil
}
